<?php
require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Admin\Table;
use App\Models\Admin\Product;
use App\Models\Admin\Voucher;
use App\Models\Admin\Bundle;
use App\Models\Admin\Order;
use Illuminate\Http\Request;

$table = Table::where('delete_status', 0)->first();
$product = Product::where('delete_status', 0)->where('product_status', 1)->first();
$bundle = Bundle::where('delete_status', 0)->with('items.product')->first();
$voucher = Voucher::where('voucher_code', 'NGOPI50')->first() ?? Voucher::first();

$controller = app(\App\Http\Controllers\Guest\OrderController::class);

echo "=== TEST A: Only Product + Voucher ===\n";
$itemsJson = [
    [
        'product_id' => $product->product_id,
        'qty' => 3,
        'note' => 'Less sugar',
    ]
];

$postDataA = [
    'table_id' => $table->table_id,
    'total_price' => (float)$product->product_price * 3,
    'items' => json_encode($itemsJson),
    'bundles' => json_encode([]),
    'voucher_code' => $voucher->voucher_code,
    'order_remark' => 'Test Catatan A',
];

$requestA = Request::create(route('guest.submit'), 'POST', $postDataA);
try {
    $resA = $controller->submit($requestA);
    echo "Status: " . $resA->getStatusCode() . " | Target: " . ($resA->headers->get('Location') ?? 'no redirect') . "\n";
    if ($resA->getSession()) {
        echo "Errors: " . json_encode($resA->getSession()->get('errors')?->all()) . "\n";
        echo "Error msg: " . $resA->getSession()->get('error') . "\n";
        echo "Success msg: " . $resA->getSession()->get('success') . "\n";
    }
} catch (\Exception $e) {
    echo "Exception A: " . $e->getMessage() . "\n";
}

echo "\n=== TEST B: With Bundle (as generated by review.blade.php) ===\n";
$bundleRowsFromReview = [
    [
        'bundle_id' => $bundle?->bundle_id,
        'bundle_name' => $bundle?->bundle_name,
        'bundle_price' => (float)$bundle?->bundle_price,
        'qty' => 1,
        // Notice in review.blade.php: bundles.map(b => ({ ... items: (b.items || []).map(...) }))
        // If b.items is missing or empty, items is []
        'items' => [],
    ]
];

$postDataB = [
    'table_id' => $table->table_id,
    'total_price' => (float)$bundle?->bundle_price,
    'items' => json_encode([]),
    'bundles' => json_encode($bundleRowsFromReview),
    'voucher_code' => '',
    'order_remark' => 'Test Catatan B',
];

$requestB = Request::create(route('guest.submit'), 'POST', $postDataB);
try {
    $resB = $controller->submit($requestB);
    echo "Status: " . $resB->getStatusCode() . " | Target: " . ($resB->headers->get('Location') ?? 'no redirect') . "\n";
    if ($resB->getSession()) {
        echo "Errors: " . json_encode($resB->getSession()->get('errors')?->all()) . "\n";
        echo "Error msg: " . $resB->getSession()->get('error') . "\n";
        echo "Success msg: " . $resB->getSession()->get('success') . "\n";
    }
} catch (\Illuminate\Validation\ValidationException $ve) {
    echo "ValidationException B: " . json_encode($ve->errors()) . "\n";
} catch (\Exception $e) {
    echo "Exception B: " . $e->getMessage() . "\n";
}
